sudo: false

language: python
python: 3.6

# Install the codecov pip dependency
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install numpy==1.16.3
  - pip install pandas==0.24.2
  - pip install scikit_learn==0.21.1
  - pip install xgboost==0.81
  - pip install bitarray==1.0.1
  - pip install tqdm==4.32.1
  - conda install -y -c pytorch faiss-cpu
  - conda install -y -c rdkit rdkit

# Run the unit test
script:
  - coverage run -m pytest test

# Push the results back to codecov
after_success:
  - codecov

